# Generated by Django 6.0.3 on 2026-05-17 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_semestre_fecha_semestre_finalizado'),
        ('usuarios', '0002_docente_facultad_alter_usuario_facultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.carrera'),
        ),
    ]
