# Generated by Django 6.0.3 on 2026-03-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_observacion', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionPonderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_asignado', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Configuraciones de Ponderación',
            },
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('alcance', models.CharField(choices=[('GLOBAL', 'Evaluación Global'), ('CURSO', 'Evaluación por Curso')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CursoDado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Cursos Dados',
            },
        ),
        migrations.CreateModel(
            name='DetalleCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_bruta', models.FloatField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionConsolidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_final', models.FloatField(default=0.0)),
                ('resumen_ia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_curso', models.FloatField(default=0.0)),
            ],
        ),
    ]
