# Generated by Django 6.0.3 on 2026-03-19 02:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CriterioEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('alcance', models.CharField(choices=[('GLOBAL', 'Evaluación Global'), ('CURSO', 'Evaluación por Curso')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_docente', models.CharField(max_length=50, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('tipo_plan', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('ciclo', models.IntegerField()),
                ('activo_para_carga', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('facultad', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluaciones.carrera')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CursoDado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='evaluaciones.docente')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.semestre')),
            ],
            options={
                'verbose_name_plural': 'Cursos Dados',
            },
        ),
        migrations.CreateModel(
            name='ChecklistObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_observacion', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('curso_dado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_realizadas', to='evaluaciones.cursodado')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionConsolidada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_final', models.FloatField()),
                ('resumen_ia', models.TextField(blank=True, null=True)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.docente')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_curso', models.FloatField()),
                ('curso_dado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.cursodado')),
                ('evaluacion_consolidada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gotas_curso', to='evaluaciones.evaluacionconsolidada')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCriterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_bruta', models.FloatField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.criterioevaluacion')),
                ('evaluacion_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_globales', to='evaluaciones.evaluacionconsolidada')),
                ('evaluacion_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_curso', to='evaluaciones.evaluacioncurso')),
            ],
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensums', to='evaluaciones.carrera')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='evaluaciones.pensum'),
        ),
        migrations.CreateModel(
            name='ConfiguracionPonderacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_asignado', models.FloatField()),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.criterioevaluacion')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.semestre')),
            ],
            options={
                'verbose_name_plural': 'Configuraciones de Ponderación',
            },
        ),
    ]
