# Generated by Django 6.0.3 on 2026-03-25 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('evaluaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistobservation',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='configuracionponderacion',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.semestre'),
        ),
        migrations.AddField(
            model_name='configuracionponderacion',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.criterioevaluacion'),
        ),
        migrations.AddField(
            model_name='cursodado',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso'),
        ),
        migrations.AddField(
            model_name='cursodado',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='cursodado',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.semestre'),
        ),
        migrations.AddField(
            model_name='checklistobservation',
            name='curso_dado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists_realizadas', to='evaluaciones.cursodado'),
        ),
        migrations.AddField(
            model_name='detallecriterio',
            name='criterio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.criterioevaluacion'),
        ),
        migrations.AddField(
            model_name='evaluacionconsolidada',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.docente'),
        ),
        migrations.AddField(
            model_name='evaluacionconsolidada',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.semestre'),
        ),
        migrations.AddField(
            model_name='detallecriterio',
            name='evaluacion_global',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_globales', to='evaluaciones.evaluacionconsolidada'),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='curso_dado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.cursodado'),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='evaluacion_consolidada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gotas_curso', to='evaluaciones.evaluacionconsolidada'),
        ),
        migrations.AddField(
            model_name='detallecriterio',
            name='evaluacion_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_curso', to='evaluaciones.evaluacioncurso'),
        ),
    ]
