# Generated by Django 6.0.3 on 2026-04-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodado',
            name='jornada',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
