# Generated by Django 6.0.3 on 2026-04-14 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_cursodado_jornada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluacioncurso',
            name='evaluacion_consolidada',
        ),
        migrations.CreateModel(
            name='AnalisisTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.JSONField()),
                ('curso_dado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.cursodado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.tipo')),
            ],
        ),
        migrations.DeleteModel(
            name='DetalleCriterio',
        ),
    ]
