# Generated by Django 6.0.3 on 2026-04-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_tipo_remove_evaluacioncurso_evaluacion_consolidada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionconsolidada',
            name='criterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.criterioevaluacion'),
        ),
        migrations.AddField(
            model_name='evaluacioncurso',
            name='criterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones.criterioevaluacion'),
        ),
    ]
