# Generated by Django 6.0.3 on 2026-04-24 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0005_evaluacionconsolidada_criterio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('datos', models.JSONField(default=dict)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='checklistobservation',
            name='datos',
        ),
        migrations.RemoveField(
            model_name='checklistobservation',
            name='titulo',
        ),
        migrations.AddField(
            model_name='checklistobservation',
            name='punteo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='checklistobservation',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='evaluaciones.checklist'),
        ),
    ]
