# Generated by Django 6.0.3 on 2026-05-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0006_checklist_remove_checklistobservation_datos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistobservation',
            name='datos',
            field=models.JSONField(default=dict),
        ),
    ]
