# Generated by Django 6.0.3 on 2026-05-11 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_semestre_fecha_semestre_finalizado'),
        ('evaluaciones', '0007_checklistobservation_datos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='academico.semestre'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
