# Generated by Django 6.0.3 on 2026-05-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0008_checklist_semestre_checklist_usuario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='punteo',
            field=models.FloatField(default=0.0),
        ),
    ]
