# Generated by Django 6.0.3 on 2026-05-08 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='SummaryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pendiente'), ('processing', 'Procesando'), ('completed', 'Listo'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='summary_states', to='evaluaciones.analisistexto')),
                ('evaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='summary_states', to='evaluaciones.evaluacionconsolidada')),
            ],
        ),
    ]
