# Generated by Django 6.0.3 on 2026-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_facultad_carrera_facultad'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semestre',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
